"""Specification output models."""

from __future__ import annotations

from typing import Any, Optional

from pydantic import BaseModel, Field


class DevelopmentTask(BaseModel):
    """A single development task in the spec."""

    task_id: str
    name: str
    owner: str = ""
    effort_days: float = 0
    priority: str = "P1"  # P0, P1, P2
    dependency: Optional[str] = None
    status: str = "Ready"


class FeatureSpecification(BaseModel):
    """Full implementation specification generated by Layer 7."""

    feature_name: str
    specification_markdown: str = ""  # The complete markdown spec
    development_tasks: list[DevelopmentTask] = Field(default_factory=list)
    evidence_citations: dict[str, str] = Field(default_factory=dict)
    total_effort_days: float = 0
    critical_path: list[str] = Field(default_factory=list)
    weekly_timeline: dict[str, str] = Field(default_factory=dict)
