"""Centralized LLM rate limit and token budget constants for the TSC pipeline."""

import os

# ─── Global Rate Limiter Capacities ──────────────────────────────────────────
# The absolute ceiling for your token buckets and queue timing.
GLOBAL_TPM_LIMIT = int(os.getenv("GLOBAL_TPM_LIMIT", 100000))
GLOBAL_RPM_LIMIT = int(os.getenv("GLOBAL_RPM_LIMIT", 14000))
GEMINI_FREE_RPM = int(os.getenv("GEMINI_FREE_RPM", 10))

# Fallback defaults for specific endpoints
GROQ_TPM_LIMIT = 4000
GROQ_RPM_LIMIT = 20

# ─── Token Budgets (max_tokens) ─────────────────────────────────────────────

# Layer 1: Ingestion
MAX_TOKENS_L1_ENTITY_EXTRACTION = 800
MAX_TOKENS_L1_PROBLEM_SYNTHESIS = 2000
MAX_TOKENS_L1_FILE_SUMMARY = 1000
MAX_TOKENS_L1_CHUNK_SUMMARY = 1500
MAX_TOKENS_L1_MERGE = 8000

# Layer 2: Discovery & Graph
MAX_TOKENS_L2_RESEARCH_QUERY = 4000
MAX_TOKENS_L2_GRAPH_SYNTHESIS = 6000
MAX_TOKENS_L2_GRAPH_CLASSIFIER = 2000
MAX_TOKENS_L2_GRAPH_ENRICHMENT = 1500

# Layer 3: Personas
MAX_TOKENS_L3_INTERNAL_STAKEHOLDER_SELECTION = 2000
MAX_TOKENS_L3_EXTERNAL_STAKEHOLDER_SELECTION = 2000
MAX_TOKENS_L3_INTERNAL_PERSONA_PROFILE = 2500
MAX_TOKENS_L3_EXTERNAL_PERSONA_PROFILE = 3000

# Layer 4 / Gates
MAX_TOKENS_L4_GATE_EVALUATION = 3000

# Layer 5: Refinement
MAX_TOKENS_L5_REFINEMENT = 3000

# Layer 6: AG2 Debate Engine
MAX_TOKENS_L6_DEBATE_SUMMARY = 600
MAX_TOKENS_L6_DEBATE_RESEARCH = 600
MAX_TOKENS_L6_DEBATE_COMPROMISE = 300

# Layer 7: Specification
MAX_TOKENS_L7_SPEC_GENERATION = 6000

# Layer 8: Handoff
MAX_TOKENS_L8_COMPLIANCE_SUMMARY = 500
MAX_TOKENS_L8_HANDOFF_NARRATIVE = 1500
MAX_TOKENS_L8_FINAL_OUTPUT = 200

# OASIS: Simulation Engine
MAX_TOKENS_OASIS_SEGMENT_INFERENCE = 6000
MAX_TOKENS_OASIS_PERSONA_BATCH = 8000
MAX_TOKENS_OASIS_SIMULATION_RESPONSE = 600

# Memory & Selection
MAX_TOKENS_HINDSIGHT_MEMORY = 600
MAX_TOKENS_HINDSIGHT_SESSION = 1000
MAX_TOKENS_WORLD_RAG = 2000
MAX_TOKENS_SYNTHETIC_EXPANDER = 600
MAX_TOKENS_TENSION_VECTOR = 2000
